### ISSUE TITLE
[Suggestion] Add option to disable giving players the guidebook on launch

### ISSUE THREAD

**Issue by choombdev** [gamma-delta/HexMod#268] opened 2022-10-22 17:14 UTC
Hey, I think there should be an option to disable giving the guidebook on launch since some packs use Akashic Tome  alongside a starter gear mod and add the guidebook in it already.

**Comment by yrsegal** [comment] 2022-11-04 20:06
duplicate of #233

**Closed by yrsegal** 2022-11-04 20:06 UTC
