### ISSUE TITLE
some text is completely unreadable on medium gui size

### ISSUE THREAD

**Issue by Hate9** [gamma-delta/HexMod#443] opened 2023-03-22 12:50 UTC
At 1080p, the guidebook contains *many* pages which are *completely* unreadable at medium GUI size.

I understand that apparently lots of people use the larger GUI sizes, but it seems like a problem, to me, that even *slightly* smaller-than-expected GUI settings makes a good nunber of pages *entirely* unreadable.

This could be fixed either by changing the font rendering (hard, not yoyr job) or by slightly reordering the pages so the text isn't absolutely tiny. I literally haven't seen patchouli books with text this small (or variable) until this mod.

**Comment by gamma-delta** [comment] 2023-03-22 22:25
(duplicate of #442 i will chat over there)

**Closed by gamma-delta** 2023-03-22 22:25 UTC

**Comment by Hate9** [comment] 2023-03-22 23:03
Oh, terribly sorry, I don't know why it did that.
