### ISSUE TITLE
[Bug?] Assessor's Reflection expects an argument on the stack

### ISSUE THREAD

**Issue by eufolim** [gamma-delta/HexMod#531] opened 2023-10-20 07:42 UTC
Hi, I noticed assessor's reflection asks for an argument on the stack, despite targeting the off-hand.
It then removes the argument (doesn't seem to mind which it is) then behaves as intended.
The book also shows it not needing an argument.

"Assessor's Reflection expected 1 or more arguments but the stack was empty"

I'm playing on forge 1.19.2 with HexCasting v0.10.3

I also have Hexal v0.2.18, MoreIotas v0.0.4 and Hex Gloop v0.0.4 installed

**Comment by object-Object** [comment] 2023-11-11 19:38
Duplicate of #375

**Closed by object-Object** 2023-11-11 19:38 UTC
