### ISSUE TITLE
Quilt/Fabric crash upon joining world

### ISSUE THREAD

**Issue by artemisSystem** [gamma-delta/HexMod#142] opened 2022-06-21 14:04 UTC
When using quilt or fabric, hexcasting seems to crash when joining a world.

- hexcasting-fabric-1.18.2-0.9.0
- paucal-fabric-1.18.2-0.4.7
- Patchouli-1.18.2-70-FABRIC
- fabric-language-kotlin-1.8.0+kotlin.1.7.0
---
- fabric-loader-0.14.8-1.18.2 + fabric-api-0.56.1+1.18.2
- quilt-loader 0.17.0-1.18.2 + qsl-1.1.0-beta.17_qfapi-1.0.0-beta.19_fapi-0.55.1_mc-1.18.2
---
Crash reports:
Fabric: https://pastebin.com/BE90ED6J
Quilt: https://pastebin.com/kfW1kN4e

**Comment by gamma-delta** [comment] 2022-06-23 19:16
Duplicate of #138 (or not technically a duplicate, but the same problem)

**Comment by artemisSystem** [comment] 2022-06-23 20:12
frogchamp, thanks

**Comment by artemisSystem** [comment] 2022-06-24 11:17
Still getting this with the latest dev build, even though #138 was marked as closed in a previous commit.

- hexcasting-fabric-1.18.2-0.9.0-pre-329
- paucal-fabric-1.18.2-0.4.7
- Patchouli-1.18.2-70-FABRIC
- fabric-language-kotlin-1.8.0+kotlin.1.7.0
---
- fabric-loader-0.14.8-1.18.2 + fabric-api-0.56.1+1.18.2
- quilt-loader 0.17.0-1.18.2 + qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2
---

Crash reports:
Fabric: https://pastebin.com/iX82SJ5i
Quilt: https://pastebin.com/S5j85niR
---
Also running into an issue i think is related: When i try to join my main world (with a bunch of other mods), it freezes (not crashes) on 0% loading. It still spat out a crashlog, here it is: https://pastebin.com/ym6En5U8

**Comment by yrsegal** [comment] 2022-06-26 13:00
This is a problem with our JiJ-ing of CC.

**Closed** 2022-06-26 13:02 UTC
