### ISSUE TITLE
[Suggestion] Add config to disable give book when player first join

### ISSUE THREAD

**Issue by elementsplayer** [gamma-delta/HexMod#233] opened 2022-08-27 08:18 UTC

**Comment by object-Object** [comment] 2023-11-11 20:00
As a workaround, you can use this datapack: https://github.com/SamsTheNerd/hexaddons/blob/c331f06705736c5907293fb73bb9afe9331d5e59/datapacks/NoHexModBookOnStart.zip

**Comment by object-Object** [comment] 2023-11-11 22:17
duplicate of #452 (this is older but there's more discussion there)

**Closed by object-Object** 2023-11-11 22:17 UTC
Labels: enhancement
