### ISSUE TITLE
[1.19 Fabric] Instant crash/freeze when attempting any Hex Spell

### ISSUE THREAD

**Issue by ImAK9** [gamma-delta/HexMod#313] opened 2022-11-21 10:26 UTC
Mod, fapi & deps versions are in the log.

Log: https://aofpaste.com/ebetiqazuc.yaml

**Comment by gamma-delta** [comment] 2022-11-21 17:18
Duplicate of #276 (tl;dr: install adoptium openjdk)

**Comment by gamma-delta** [comment] 2022-11-21 17:22
Whoops apparently this is with openjdk. Also TIL normal users can't reopen issues themselves.

**Comment by gamma-delta** [comment] 2022-11-21 20:48
OK we switched to Cloth config it should work now

**Closed by gamma-delta** 2022-11-21 20:48 UTC
