### ISSUE TITLE
Hexcasting not loading gravity changer hexes with gravity api

### ISSUE THREAD

**Issue by walksanatora** [gamma-delta/HexMod#394] opened 2023-01-26 18:39 UTC
gravity api is a maintained fork of gravity changer, since gravity changer is dead why not use gravity api
https://modrinth.com/mod/gravity-api
they do the exact same thing (i think they even use the same api)

**Comment by gamma-delta** [comment] 2023-01-30 18:53
Duplicate of #362

**Closed by gamma-delta** 2023-01-30 18:53 UTC
