### ISSUE TITLE
Can't overwrite scrolls with other patterns

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#51] opened 2022-04-01 00:21 UTC
### Versions
Minecraft: 1.18.2
Forge: 40.0.34
Hex: Commit [767dd99](https://github.com/gamma-delta/HexMod/commit/767dd9983d14088ce6732cab62380b6788770c10)
Paucal: Commit [8f64bef](https://github.com/gamma-delta/PAUCAL/commit/8f64bef48e7a6fe3487c9f460fc3037b1b72803f)
### Issue
Scrolls cannot be written to if there's already a pattern stored in the scroll.
For example, empty scrolls can be written to (Consideration, pattern, Scribe's Gambit) but after that, it cannot be written to anymore.
The error given in chat is:
**operator expected at.petrak.hexcasting.common,items.ItemDataHolder in offhand but got 1 scroll**
This bug was encountered on the supporter Hexcasting server.

**Comment by gamma-delta** [comment] 2022-04-03 15:44
That's intended behavior.

**Comment by gamma-delta** [comment] 2022-04-03 15:44
(The janky mishap message is fixed on the bleeding-edge)

**Closed by gamma-delta** 2022-04-03 15:44 UTC
