### ISSUE TITLE
[Suggestion] Expand Impulse's functionality

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#250] opened 2022-09-17 03:51 UTC
Impulse currently pushes a given entity along the vector at its magnitude, in blocks, per tick
I suggest having Impulse take in more than one kind of input, allowing it to work on a vector as well as entities
When used on a vector, the block at that vector is turned into a falling block and then moved along the vector at its magnitude, in blocks, per tick
This would require a check similar to Botania's Weight lens check, to prevent fragile blocks like Budding Amethyst to be collected
This adds more things Hex is capable of doing while also saving patterns

**Comment by gedeknepper** [comment] 2022-10-16 19:09
Hexal (an add-on) has a pattern for that. It turns the block at a given location into a falling block. Falling blocks, I've confirmed, can be acted on by Impulse.

**Comment by object-Object** [comment] 2023-11-11 19:57
Closing as out of scope since Hexal already has this.

**Closed by object-Object** 2023-11-11 19:57 UTC
Labels: out of scope
