### ISSUE TITLE
Client Crash with Hex Casting on a server (java.lang.ClassNotFoundException: at.petrak.paucal.api.contrib.Contributors)

### ISSUE THREAD

**Issue by ThugPug43** [gamma-delta/HexMod#107] opened 2022-06-09 04:14 UTC
The crash apparently happens when casting.
https://pastebin.com/Zwj8xhSk

**Comment by ThugPug43** [comment] 2022-06-09 18:51
I think it might be the soulglimmer pigment causing the issue

**Comment by gamma-delta** [comment] 2022-06-09 18:57
What version of PAUCAL are you on? For Hexcasting 0.8.3 you want 0.3.4.

**Comment by gamma-delta** [comment] 2022-06-09 18:58
Duplicate of #105; go to that issue please.

**Closed by gamma-delta** 2022-06-09 18:58 UTC
