### ISSUE TITLE
Error sound effect doesn't play in multiplayer

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [gamma-delta/HexMod#48] opened 2022-03-31 02:58 UTC
### Versions
Minecraft: 1.18.2
Forge: 40.0.34
Hex: Commit [767dd99](https://github.com/gamma-delta/HexMod/commit/767dd9983d14088ce6732cab62380b6788770c10)
Paucal: Commit [8f64bef](https://github.com/gamma-delta/PAUCAL/commit/8f64bef48e7a6fe3487c9f460fc3037b1b72803f)
### Issue
It simply doesn't play if you're in multiplayer.
Any error that would've played the sound effect (missing args, couldn't match pattern to iota, etc) doesn't play the sound effect.
Encountered this on the patron server.

**Comment by yrsegal** [comment] 2022-04-09 01:27
can't reproduce?

**Comment by GameGuruGreenGryphon** [comment] 2022-04-09 17:47
It probably has something to do with the Hex version mismatch between client and server, so it'll probably resolve itself when the server's updated.

**Comment by gamma-delta** [comment] 2022-05-03 14:47
Any word on this?

**Comment by gamma-delta** [comment] 2022-06-09 18:58
I've observed the sound working on Blanketcon so I'm gonna close this.

**Closed by gamma-delta** 2022-06-09 18:58 UTC
